name: Deploy React Application in the production repository

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]

# Continue build and deployment even if there are warnings
env:
  CI: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_to_prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # We will deploy with only one version of node

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: replace homepage URL
        run: |
          sed -i 's?UKCORDEX-plot-explorer-dev?UKCORDEX-plot-explorer?g' package.json
          grep "UKCORDEX-plot-explorer.git" package.json
          grep "UKCORDEX-plot-explorer/" package.json
      - name: npm ci and build
        run: |
          npm ci --force
          npm run build --if-present
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          repository-name: UCL/UKCORDEX-plot-explorer
          token: ${{secrets.DEPLOYMENT_TO_PROD}}
